### ISSUE TITLE
Lang - Hungarian

### ISSUE THREAD

**Issue by Jmos** [neard/neard#112]
[Hungarian - magyar **1.4**](https://github.com/neard/neard/files/1596061/hungarian.zip)

[Hungarian - magyar **1.3**](https://github.com/crazy-max/neard/files/1337290/hungarian.zip)

[Hungarian - magyar **1.2**](https://github.com/crazy-max/neard/files/992431/hungarian.zip)

[Hungarian - magyar **1.0.22**](https://github.com/crazy-max/neard/files/696683/hungarian.zip)

[Hungarian - magyar **1.0.21**](http://pastebin.com/pVxXyHfX)

**Comment by crazy-max** [comment]
Hi!

Thanks for contrib!

The missing chars come from a limitation of Aestan Tray Menu.
I'm currently working on a v2 of Neard in JavaFX to remove Aestan Tray Menu.

I will try to fix this problem and implement your translation in the next release.

**Comment by Jmos** [comment]
Re: [neard] Hungarian Translation (#112)



Hello Cr,

Ok Waiting for the new release 

Sunday, March 20, 2016, 11:26:57 PM, you wrote:





Hi!
Thanks for contrib!
The missing chars come from a limitation of Aestan Tray Menu.
I'm currently working on a v2 of Neard in JavaFX to remove Aestan Tray Menu.
I will try to fix this problem and implement your translation in the next release.
—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub





-- 
Best regards,
Tel: +36 70 599 79 17
       + 36 20 776 95 14
 Meggyeshazi                            mailto:janos.meggyeshazi@gmail.com

**Comment by crazy-max** [comment]
I've got bad format error, can you check those lines :

* switchVersionOkRestart (line 126)
* aliasRemoveError (line 160)

Thanks

**Comment by Jmos** [comment]
Unfortunately I didn't find any malformed line I retyped those two line but both has @nl@ sequence. Can put any space before or after it?
[neard_hungarian_translation(2).zip](https://github.com/crazy-max/neard/files/210758/neard_hungarian_translation.2.zip)

**Comment by crazy-max** [comment]
The bad formats come from my internal unit testing, not the final result. Here is why for example :

In english on line 126 we have :
`switchVersionOkRestart = "%s version switched successfully to %s@nl@Press OK to restart %s ..."`

Contains 3 `%s` and 1 `@nl@`

In your hungarian file you have :
`switchVersionOkRestart = "A %s verzió sikeresen cserélve %s-re@nl@Nyomj OK-t újraindításhoz"`

Contains 2 `%s` and 1 `@nl@`
So one `%s` is missing .

Thanks!

**Comment by Jmos** [comment]
Sorry I look but not see but now is corrected
[neard_hungarian_translation(3).zip](https://github.com/crazy-max/neard/files/210974/neard_hungarian_translation.3.zip)

**Comment by crazy-max** [comment]
Ok thanks

I looked for the problem with special chars and unfortunately Aestan Tray Menu cannot handled these chars `ő Ő ű Ű`.
So i implement a functionnality to replace on fly the chars `ő Ő ű Ű` with standard chars `o O u U`.
Do you notice others missing chars ?

**Comment by Jmos** [comment]
No other accent chars seems be correct

**Comment by crazy-max** [comment]
Ok thanks for your time!

**Comment by crazy-max** [comment]
Added on Neard 1.0.18
I will keep that ticket opened to notify you if i change languages
Thanks for your support!

**Comment by crazy-max** [comment]
Some changes have been made, please check [this diffrences](https://github.com/crazy-max/neard/commit/c280bccaa1aa1824e87eb5e4d38d773cc0d27f59#diff-85f40e111ca1cc6ca5be49b33b00495a) from the latest release (1.0.18) and send me back your .lng
Thanks!

**Comment by crazy-max** [comment]
Since 1.0.19 :

```
=> Missing: N/A
=> Bad format: N/A
=> Not translated: 21
  gitConsole (line 22)
  license (line 26)
  svnConsole (line 42)
  verboseTrace (line 48)
  menuChangeRootPwd (line 59)
  aliasNotValidAlpha (line 176)
  vhostNotValidDomain (line 194)
  vhostCreated (line 196)
  changeDbRootPwdTitle (line 207)
  changeDbRootPwdCurrentpwdLabel (line 208)
  changeDbRootPwdNewpwd1Label (line 209)
  changeDbRootPwdNewpwd2Label (line 210)
  changeDbRootPwdNotsameError (line 211)
  changeDbRootPwdIncorrectError (line 212)
  changeDbRootPwdText (line 213)
  startupUpdateConfigText (line 230)
  startupCheckServiceText (line 231)
  checkVersionChangelogText (line 286)
  homepageAboutHtml (line 314)
  homepageLicenseText (line 315)
  homepageMailhogText (line 320)
```

**Comment by crazy-max** [comment]
Since 1.0.20 :

```
=> Missing: N/A
=> Bad format: N/A
=> Not translated: 23
  administration (line 11)
  downloadMore (line 20)
  gitConsole (line 24)
  license (line 28)
  svnConsole (line 44)
  verboseTrace (line 50)
  menuChangeRootPwd (line 61)
  aliasNotValidAlpha (line 178)
  vhostNotValidDomain (line 196)
  vhostCreated (line 198)
  changeDbRootPwdTitle (line 209)
  changeDbRootPwdCurrentpwdLabel (line 210)
  changeDbRootPwdNewpwd1Label (line 211)
  changeDbRootPwdNewpwd2Label (line 212)
  changeDbRootPwdNotsameError (line 213)
  changeDbRootPwdIncorrectError (line 214)
  changeDbRootPwdText (line 215)
  startupUpdateConfigText (line 232)
  startupCheckServiceText (line 233)
  checkVersionChangelogText (line 288)
  homepageAboutHtml (line 316)
  homepageLicenseText (line 317)
  homepageMailhogText (line 322)
```

**Comment by Jmos** [comment]
I hope it's not to late
[hungarian translation 1.0.20](https://github.com/crazy-max/neard/files/350173/hungarian.zip)

**Comment by crazy-max** [comment]
Never too late! Thanks

**Comment by crazy-max** [comment]
Will be available in the next release.

**Comment by crazy-max** [comment]
Since 1.0.21 :

```
=> Missing: N/A
=> Bad format: N/A
=> Not translated: 7
  disabled (line 17)
  enabled (line 22)
  menuEnable (line 70)
  startServiceTitle (line 174)
  enableTitle (line 316)
  enableBundleNotExist (line 317)
  homepageAboutHtml (line 334)
```

**Comment by Jmos** [comment]
Latest see first post

**Comment by crazy-max** [comment]
Great thx!

**Comment by crazy-max** [comment]
Since 1.0.22 :

```
=> Missing: N/A
=> Bad format: N/A
=> Not translated: 3
  pythonConsole (line 36)
  pythonCp (line 37)
  enableBundleNotExist (line 323)
```

**Comment by Jmos** [comment]
[hungarian.zip](https://github.com/crazy-max/neard/files/696683/hungarian.zip)
1,0,22 hun lang

**Comment by crazy-max** [comment]
Thanks! :)

**Comment by crazy-max** [comment]
For the next release some changes have been made :

```
=> Missing: N/A
=> Bad format: N/A
=> Not translated: 2
  statusPage (line 48)
  homepageAboutHtml (line 345)
```

Thanks for your time!

**Comment by Jmos** [comment]
[hungarian 1.0.23](https://github.com/crazy-max/neard/files/839598/hungarian.zip)
maybe 1.0.23 if it a next version

**Comment by crazy-max** [comment]
Yep it will be ;)
Thanks!

**Comment by crazy-max** [comment]
For the next release some changes have been made :

```
=> Missing: N/A
=> Bad format: N/A
=> Not translated: 3
  statusPage (line 49)
  menuUpdateEnvPath (line 96)
  homepageAboutHtml (line 348)
```

Thanks for your time!

**Comment by Jmos** [comment]
[hungarian update](https://github.com/neard/neard/files/1596061/hungarian.zip)

**Comment by crazy-max** [comment]
Thanks again @Jmos !

**Comment by crazy-max** [comment]
@Jmos New changes since 1.7:

```
=> Missing: N/A
=> Bad format: N/A
=> Not translated: 3
  restartServiceTitle (line 188)
  restartServiceError (line 189)
  startupSysInfos (line 248)
```

**Comment by Jmos** [comment]
Re: [neard/neard] Lang - Hungarian (#112)


Hello  CrazyMax,

I am so busy but I have time i will translate 
Can you send some message before you publish new release 
thanx

======================
mailto:janos.meggyeshazi@gmail.com
Best regards,
Tel:  + 36 20 776 9514
======================

======================
Meggyeshazi Janos
Sunday, April 5, 2020, 8:24:27 PM, you wrote:
======================




@Jmos New changes since 1.7:
=> Missing: N/A
=> Bad format: N/A
=> Not translated: 3
  restartServiceTitle (line 188)
  restartServiceError (line 189)
  startupSysInfos (line 248)
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.



======================

**Comment by Jmos** [comment]
Hungarian language file 
[1.7 version here](https://github.com/neard/neard/files/4440917/hungarian.zip)

**Comment by crazy-max** [comment]
Thanks @Jmos !
