### ISSUE TITLE
Create an installer

### ISSUE THREAD

**Issue by iansebryk** [neard/neard#136]
i appreciate this may be a stupid question, but HOW do i upgrade to the new release without blowing away my databases and settings?  i've looked everywhere (i think) for an answer, but no such luck.  forgive me if this is a stupid question, but this stupid questioner would like to know.  :)

**Comment by crazy-max** [comment]
Hi, all instructions tu upgrade from previous release are added in the [CHANGELOG.md](https://github.com/crazy-max/neard/blob/master/CHANGELOG.md) for each release.
See the [FAQ on the Wiki](https://github.com/crazy-max/neard/wiki/FAQ).
Note: If for example you are on 1.0.17 and want to upgrade to 1.0.19 you have to update first to 1.0.18 and follow the instructions in the CHANGELOG.md.

**Comment by iansebryk** [comment]
okay.  upgrade complete and working great.  my only remaining question then is can we simple replace the .conf file instead of adding/changing the lines?  just trying to minimize tedium moving forward with a little Perl perhaps...  :)

**Comment by crazy-max** [comment]
Mmmh no you can't overwrite the conf file because you can have many different versions of bins / tools / applications.
I will implement a new way to upgrade with a basic setup based on InnoSetup in the next release.

**Comment by dmccan** [comment]
I think an update function would be more useful than an installer.  Maybe show the installed version and the latest version and let the user click a button.  When clicked the new version is downloaded, the old folder is renamed, the old config section is commented, the new version is copied in and the new config written in.  If there were no errors then a cleanup removes the old stuff or if there was an error show the message and put the old stuff back.

**Comment by crazy-max** [comment]
Yep when i said a setup it can be an update or a clean install.
And in the case of an update InnoSetup can detect the current installation path but a registry entry has to be added
For the rest i agree

**Comment by N6REJ** [comment]
@crazy-max I'm having a issue with inno on a program I'm writing to detect if mysql is locked or not, for the cloud use we talked about before.  I've got it all working 100% EXCEPT that when its shows the install directory its not showing the one that I mention in the video I'll be releasing this week.
my current iss is 
`; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Wamp Safe Start"
#define MyAppVersion "1.0"
#define MyAppPublisher "Bear's Tips & Tricks - Troy T. Hall"
#define MyAppURL "http://www.hallhome.us"
#define MyAppExeName "wampsafestart.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{82CE09F7-450B-465C-B192-496B8792126A}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
CreateAppDir=no
LicenseFile=C:\Users\Bear\Desktop\wampsafestart\gpl.txt
InfoBeforeFile=C:\Users\Bear\Desktop\wampsafestart\wampsafestart-intro.txt
OutputDir=C:\Users\Bear\Desktop\wampsafestart\installer
OutputBaseFilename=WampSafeStart_Setup
SetupIconFile=C:\Users\Bear\Desktop\wampsafestart\wampsafestart_X5S_1.ico
Compression=lzma
SolidCompression=yes
MinVersion=6.1.7600

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"


[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"


[Icons] 
Name: "{userstartup}\Wamp Safe Start"; Filename: "{app}\wampsafestart.exe"

[Files]
Source: "C:\Users\Bear\Desktop\wampsafestart\wampsafestart.exe"; DestDir: "c:\google_drive\server\wamp64"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
`  
This is my very first time ever doing this so I could be doing it all wrong.

**Comment by crazy-max** [comment]
Hi @N6REJ,

Some track to detect if mysqld.exe is launched :

* https://stackoverflow.com/questions/9941293/how-to-check-with-inno-setup-if-a-process-is-running-at-a-windows-2008-r2-64bit
* http://www.vincenzo.net/isxkb/index.php?title=PSVince

Anbd what do you mean by "that I mention in the video" ? Do you have a link ?

**Comment by N6REJ** [comment]
in our use that won't work because if its open on another machine there won't be a local process :D  Which is why I made my checked for a locked mysql.  If its locked it doesn't matter what else is going on simply stop and fix it.  I'll have my video up and running hopefully today, spent all yesterday perfecting the installer.  My work for the safe start is here .. https://github.com/N6REJ/Wamp-Safe-Start

**Comment by crazy-max** [comment]
Ok thanks

**Comment by r-a-y** [comment]
It would be useful to have an installer to omit certain applications from being included.

Currently, the extracted filesize is 1.4GB, which is quite large.

**Comment by Wizard13** [comment]
I agree 100% with being able to omit installing certain applications. In fact, I would suggest an additional core package with just the minimum (neard.exe, other necessary files, apache, php and only one database), so that we don't have to download such huge modules like perl, git, python, etc. In that way, we can choose the rest of the modules and download them.

**Comment by crazy-max** [comment]
Latest release now includes "basic" and "light" packages: https://neard.io/release/1.8.0/
