### ISSUE TITLE
Allow to run only a single instance (local and/or network)

### ISSUE THREAD

**Issue by N6REJ** [neard/neard#267]
This one little "trick" is the entire key to using wamp on a network.  While wamp doesn't include precautionary mysql startup, it does provide everything else in 2 easy clicks to make it work on a network/cloud environment.  
With the code I've created it's very easy to test for an existing .pid and NOT start "wamp" as its currently not safe since .pid's are machine specific.  
This code could be easily built into the wampmanager to provide this function natively.

**Comment by crazy-max** [comment]
Ok thanks for your feedback

**Comment by N6REJ** [comment]
Here's my code @crazy-max https://github.com/N6REJ/Wamp-Safe-Start

**Comment by crazy-max** [comment]
Ok thanks i see what you mean

**Comment by crazy-max** [comment]
@N6REJ I'll come back to this ticket. You can not rely on MySQL to detect that an instance is already running because MySQL is a module (which can be disabled) and is not part of Neard's core.
I'll look for another way to detect that Neard is already running.

**Comment by crazy-max** [comment]
There is not really an effective and robust way to implement this feature. Feel free to open PR if you want to work on it.
