### ISSUE TITLE
Move neard repositories to its organization 🎉

### ISSUE THREAD

**Issue by crazy-max** [neard/neard#339]
Will be moved to : https://github.com/neard
Special thanks to @dougburkhalter for changing his username :upside_down_face:

**Comment by N6REJ** [comment]
awesome!! congrats!

**Comment by crazy-max** [comment]
Was a long process but done : https://github.com/neard
If someone has the slightest problem related to the creation of the organization or if you have any suggestions, do not hesitate to post an issue.
