### ISSUE TITLE
Apache fails to start post-1709 update

### ISSUE THREAD

**Issue by iansebryk** [neard/neard#341]
of the plethora of problems that followed in the wake of Win10 1709 update, this is one of the most pressing:  Apache won't start.  something is already using port 80... but what?  have no friggin' idea.  all i did was reboot.  here's the logs, core/tmp and screenshot.

Win10 Pro x64 1709 (build 16299.15).  zipped logs and core/tmp:  https://goo.gl/bBnTrz

![neard-apacheerror](https://user-images.githubusercontent.com/1943574/33625859-371fcce0-d9b6-11e7-8125-08f6effe4eb8.png)

**Comment by crazy-max** [comment]
Hi @iansebryk, thanks for your input i will take a look and keep you in touch asap. Thanks.

**Comment by iansebryk** [comment]
for the love of.... !@#$.  found what might have been the problem.  after the 1709 update, for reasons that esape me, IIS was turned on (you can imagine the fun that created on my network...).  i turned that POS back off and Presto!  Apache mounts up no problem.  now i get to focus back on the SMB debacle... today is Monday 2.0...  💩

**Comment by crazy-max** [comment]
@iansebryk Ok, i will add a note about this in the FAQ thanks ;)

**Comment by N6REJ** [comment]
@iansebryk I sent a reply via email but apparently it got lost or blocked, in the apache services tab of neard there is a port 80 checker and changer.

**Comment by crazy-max** [comment]
@iansebryk Was already in the FAQ :roll_eyes: : http://neard.io/doc/faq/#iis-conflict-port-80-and-443
