### ISSUE TITLE
The system cannot find the file specified.

### ISSUE THREAD

**Issue by gamevnlc** [neard/neard#356]
Neard version 1.4
OS Window 10
Python is not working, it show this message 
"The system cannot find the file specified."
when I run python from console
I tried to debug in when running python.bat, It seem that this code is not work in neard\tools\python\python3.6.0.1\scripts\env,bat
`echo ;%PATH%; | %FINDDIR%\find.exe /C /I ";%WINPYDIR%\;" >nu`

**Comment by N6REJ** [comment]
works fine for me, neard 1.4, win 10 x64 pro
![image](https://user-images.githubusercontent.com/1850089/34749790-fd35c6e6-f568-11e7-96db-06ba582a038a.png)

**Comment by crazy-max** [comment]
@gamevnlc Please review your issue : http://neard.io/doc/reporting-issue/
Thanks

**Comment by gamevnlc** [comment]
@crazy-max 
I have figured out the problem. Because the Null Service in my computer can't start. I have restart the service and python is working now
