### ISSUE TITLE
Git not work

### ISSUE THREAD

**Issue by gamevnlc** [neard/neard#357]
Neard v 1.4
OS Window 10
I tried to run git from git console but it show this message
fatal: open /dev/null or dup failed: No such file or directory

**Comment by N6REJ** [comment]
Works fine for me.. 
![image](https://user-images.githubusercontent.com/1850089/34749672-60b8225a-f568-11e7-97c7-7f96d9b62d9c.png) neard 1.4 , win 10 x64 pro

**Comment by crazy-max** [comment]
@gamevnlc Please review your issue : http://neard.io/doc/reporting-issue/
Thanks

**Comment by gamevnlc** [comment]
@crazy-max 
I have figure out why  git is not working because the Null Service in my computer can't start. I have restart the service and git is working now .
