### ISSUE TITLE
Environment variable and Neard 1.4

### ISSUE THREAD

**Issue by Julienh** [neard/neard#359]
Hello and thank you for your work :)

I have a problem with NodeJS and Neard 1.4, I have NodeJS installed on my computer with some apps, the problem is on each Neard restart, Neard update the %NEARD_BINS% in "path" environment variable on the first place so I can't use my NodeJS path.
Same problem if I delete the NodeJS path on NEARD_BINS.

How can I do to fix my problem please ? 
Thank you

**Comment by crazy-max** [comment]
Hi @Julienh, you can disable node on Neard :

* Stop Neard
* Edit `neard.conf` with `nodejsEnable = "0"`
* Start Neard

Thanks for your support

**Comment by Julienh** [comment]
Thank you !
