### ISSUE TITLE
Services cannot start / paused on Win 10 Creators Update - wave 2

### ISSUE THREAD

**Issue by svatas** [neard/neard#360]
Looks like I have the same issue as mentioned in #242

This time this is only for Apache. I started with version 1.4 and downgrded to version 1.3. Still the same.

As this is across version I think it is the problem of nssm.exe. But I can see in my registry that AppNoConsole is setup to 1. But still, not working.

**Comment by crazy-max** [comment]
Hi @svatas, can you read and apply the [SUPPORT page](https://github.com/neard/neard/blob/master/.github/SUPPORT.md) please ?

Also can you give me your Windows version (type `winver` in cmd and paste the screenshot here) ?

Thanks

**Comment by svatas** [comment]
I have Windiows 10 Pro

This is winver :
![image](https://user-images.githubusercontent.com/2070628/36101875-dc6c0328-100a-11e8-8fc6-894f810c10e0.png)

Error message :
![image](https://user-images.githubusercontent.com/2070628/36102122-954e349c-100b-11e8-803a-363ce82631fa.png)

Link to logs : http://www.uschovna.cz/en/zasilka/VMW3L2NX3XR6VR5C-V9G/

**Comment by svatas** [comment]
Neard is 1.3, but the same is on 1.4

**Comment by crazy-max** [comment]
Ok thanks i keep you in touch

**Comment by N6REJ** [comment]
@svatas have you ran the check port 80 utility to see if its in use?

**Comment by crazy-max** [comment]
@svatas, I've created a new virtual machine based on Windows 10 Pro 16299.192 and i cannot reproduce your issue :

![image](https://user-images.githubusercontent.com/1951866/36126037-fd8024a8-1056-11e8-9226-ba6818024205.png)

And in the logs you put only the tmp directory and not the logs directory. Can you send them back?

**Comment by N6REJ** [comment]
@crazy-max I'm wondering if he's having a skype conflict with port 80?  Wouldn't that cause it?

**Comment by crazy-max** [comment]
Maybe but i hope he had read the [FAQ](http://neard.io/doc/faq/) ;)

**Comment by svatas** [comment]
Back to the basics :)

looks that it will be important to check small details.

1) I installed Neard 1,4 and worked with it without any problem (tested CMS GRAV). I am an editor of local web sw magazine and was preparing screenshots to my review of Grav. I worked with Neard for whole day
2) I restarted my computer and want to continue with creating screenshots
3) Errror message appeard
4) I uninstalled Neard and installed again
5) I reinstalled Neard 1,4 to 1.3
6) The same error was here
7) I used similar product (EasyPHP) and apache is working as expected
8) I uninstalled EasyPHP and installed Neard again - no change

This is to summaize all ations. This can explain why you can not reproduce. However pretty strange is , that when some other product is atrted, there is no problem with Apache.

Sorry for the missing logs. Please use new link 
http://www.uschovna.cz/en/zasilka/VNBXBPTKG654VNAR-WND/ 

Skype is not a problem it is not used. As an evidence I can proove it by the first day when I was using Neard. it was working properly.

**Comment by N6REJ** [comment]
2 questions.. have you ran the port 80 check function?  It's in the apache area..
and are you shutting down nerd before reboot?
the fact that it was working fine seems to point to it NOT being neard, you did install the prereq i assume?

**Comment by svatas** [comment]
So after many tries and examination I found, where the problem is. When ther is VMWARE WORKSTATION PLAYER 12 installed, it also installs services, which prevents Neard to install Apache service.
As those services are started even you are not using VMWARE, the only solution is to stop them. In many cases they are automatically started again. The workaround is to change their way of start to Manual from Automatic.

From that perspective - is there something which can improve this behaviour of Neard in this area? Something like automatic reconfiguration if VMWARE services detected?

**Comment by crazy-max** [comment]
@svatas we won't handle every application in the world that uses port 80. I hope you understand :upside_down_face:

However, as @N6REJ says, you can use the menu in Neard to check which application uses port 80 :

![image](https://user-images.githubusercontent.com/1951866/37836461-ca5c9fbe-2eb2-11e8-88e2-6bfea1dce6f2.png)
