### ISSUE TITLE
About adding new vhost

### ISSUE THREAD

**Issue by haydarsahin34** [neard/neard#363]
Hello, thanks for developing neard. I have a new feature suggestion.  I think definitely that neard
should can create new folder on www folder and change host file while adding new host.

Again thanks for this good project

**Comment by crazy-max** [comment]
Hi @haydarsahin34,

This is an old feature (see #1 :upside_down_face:) that needs to be implemented indeed ;)
And you're welcome!

Thanks for your contrib
