### ISSUE TITLE
spaces in nssmEnvPath.dat remove all environment isolation

### ISSUE THREAD

**Issue by croensch** [neard/neard#365]
Hi, if i put a path with spaces in nssmEnvPath.dat like `C:\tools\bo gus`. Then call some php script via apache `getenv('PATH')` it shows all system paths (instead of the wanted path) - so the [isolation](http://neard.io/doc/faq/#path-env-var-is-not-resolved-by-apache-service) is broken.

**Comment by crazy-max** [comment]
Hi @croensch, i will take a look

**Comment by crazy-max** [comment]
Closed due to inactivity
