### ISSUE TITLE
npm not functioning properly.

### ISSUE THREAD

**Issue by N6REJ** [neard/neard#366]
I'm trying to run browsersync and when I go to npm console and tell it.
> cd www/css-grid 
npm i
> npm install -g browser-sync

I get a VERY long delay and then it errors.. I"m including the log that it reported.
![image](https://user-images.githubusercontent.com/1850089/37891487-21f3ad24-309a-11e8-9b43-41c84f9aac05.png)

[2018-03-26T06_57_28_038Z-debug.log](https://github.com/neard/neard/files/1846651/2018-03-26T06_57_28_038Z-debug.log)

info:
Win 10 x64 pro
neard: 1.4

p.s. I'm doing this so that I can follow along with this course  [css-grid](https://courses.wesbos.com/account/access/5aac534b4f754d18086b49ef/view/249523152)

**Comment by crazy-max** [comment]
This issue is related to browser-sync and/or npm, not Neard.
If you read the logs you will have a clue :

```
1720 verbose optional Please try running this command again as root/Administrator.
```

**Comment by crazy-max** [comment]
I don't have any issue to install browser-sync with node 8.9.3 :

![image](https://user-images.githubusercontent.com/1951866/38019801-e52958b8-3278-11e8-95c0-e7ab966732d8.png)

Try to remove folder `C:\neard\bin\nodejs\nodejs8.9.3\node_modules\browser-sync` (it seems busy by an other process)

**Comment by N6REJ** [comment]
@crazy-max Max I've done everything I can think of including removing node folder and replacing it.. 
can you please try to do "npm i -g npm" if your running < 5.8?

**Comment by crazy-max** [comment]
Node/npm cannot and must not be updated itself! This can cause issues with paths and npm. You have to download the official Neard releases.

**Comment by N6REJ** [comment]
thats what I did, but ok.. hmmm I wonder if phpstorm changed things... but even with neard off it didn't work so, least that gives me a direction to go.  Thanks.
