### ISSUE TITLE
change/create git bash configs in Win10

### ISSUE THREAD

**Issue by iansebryk** [neard/neard#367]
heyo.

i'd like to be able to deploy a .bashrc for the git bash console in Win10.  i hate the default font & colours and, as a Linux user, have my own configs that i want to bring across.  where would i put these so the console will read them and implement them?  they aren't being read from the home directory... :P

thanks.  :D

**Comment by crazy-max** [comment]
Hi @iansebryk, take a look at this thread if you want to use your own .bashrc : https://stackoverflow.com/questions/6883760/git-for-windows-bashrc-or-equivalent-config-files-for-git-bash-shell
On Neard, git bash is available here : `\neard\tools\git\gitx.x.x\git-bash.exe`

**Comment by iansebryk** [comment]
meant to give feedback here on this.  if you name the file .bash_profile and place it in the neard path, AND run it directly, the bash settings work.  however.  if you call it .bashrc, it won't work.  if you launch it from the tools menu in the system tray, it won't work.  and, finally, if you place it in your home directory and call it either name, it won't work.  so.  until i have time to troubleshoot a little more, directly launch bash_console.exe from the path with a .bash_profile and it will work as expected...  whew...  😌
