### ISSUE TITLE
Add Golang

### ISSUE THREAD

**Issue by qodrinzo** [neard/neard#373]
Golang is worth being a neard-module too, I think!

**Comment by crazy-max** [comment]
@qodrinzo What is the main purpose to make Golang as a Neard's module for you ? You use Go for embedded webapps services ? Please explain a little more your need and use cases. Thanks

**Comment by qodrinzo** [comment]
@crazy-max Yes, I use it usually for web development; but to be honest, I use Neard as a **portable** stack of development tools rather than just for _web_ development. I use Python inside the stack to download/program anything it could do, for example...
I can add Golang myself if I know how Neard sets Environment variables at each start-up and removes when it stops.

**Comment by crazy-max** [comment]
@qodrinzo Of course you can. But you can also contribute by creating a module for Go :)
You can have an exemple with #334 and here : https://github.com/neard/neard/commit/0db95883364119874678b385ca4cd9aa7d5c732b
Let me know if you have any questions.
