### ISSUE TITLE
can this run, services stopped, with WebGoat?

### ISSUE THREAD

**Issue by iansebryk** [neard/neard#374]
can i leave Neard running with services disabled and still run WebGoat?  since it binds to localhost as well, i don't know if there would be a conflict or not.  again, Neard services would all be STOPPED.

cool if YES,  no big deal if NO.  thanks!  😄 

EDIT:  nevermind.  i thought WebGoat was the server, that's WebWolf...  got my wires crossed.  since it's an APPLICATION, we should be able to run it on Neard, yes?  apologies for muddying the water...  😞

**Comment by crazy-max** [comment]
`localhost` is a hostname that means *this computer* or `127.0.0.1` ip address.
It is not the problem. The problem could be the port assigned to WebGoat. If WebGoat uses port 80 you have to switched Apache to 81 for exemple and it will be ok i think ;)
