### ISSUE TITLE
Add Lighttpd

### ISSUE THREAD

**Issue by iansebryk** [neard/neard#375]
two reasons: 1) more and more of my clients are using Lighttpd and 2)  tired of all the Apache errors on startup.  runs find for a while, then a reboot or logout and BAM.  stops working and always right when i need it most.  💥 if i can just swap in Lighttpd, that would be awesome.  if not, then let me know and i'll build up another log/error package for the issue (Error 7).

**Comment by crazy-max** [comment]
Yep I could add Lighttpd as a new module but #327 has to be finished first (same case as #165)

**Comment by iansebryk** [comment]
that's wonderful.  💯   thanks for all your amazing work.  😃

**Comment by iansebryk** [comment]
heyo.  your favourite PITA here.  just seeing if this is making any progress?  my system literally burned to the ground while i was on holiday and so i'm rebuilding (everything) and thought i'd see if this/nginx were modularized..able?  no pressure, just curious.  and forgive me if you responded to this via other channels: mail server ate the flames too...  :P

**Comment by crazy-max** [comment]
Hi @iansebryk,

Oh sorry to hear that! Otherwise nothing has changed from my previous comment but PR are more than welcome :wink:
