### ISSUE TITLE
okay.  enough of Apache's crap.  what's broken here?

### ISSUE THREAD

**Issue by iansebryk** [neard/neard#376]
suddenly started getting these errors and Apache is not starting.  torched my install and installed brand new version fresh from here.  bam.  error.  have no idea what the hell is going on.  i finally got curious about the logs and took a look... why do you need an extract of ALL running procs?  because i'm not terribly comfortable with that.  at any rate, here's my logs and screenshots of the error.

![neard-apache-error](https://user-images.githubusercontent.com/1943574/40524659-ee701f9a-5f98-11e8-9275-df3800dc48e4.jpg)

before i blew away the old install and replaced it with this one, i would also get this error when i tried to look at the logs (and the files were definitely there...):

![neard-aestan-error](https://user-images.githubusercontent.com/1943574/40524678-15013b76-5f99-11e8-939e-3414905dfa0c.jpg)

LOGS:  [apache-status-7-error-logs.zip](https://github.com/neard/neard/files/2037877/apache-status-7-error-logs.zip)

**Comment by crazy-max** [comment]
Service seems busy : `- Cannot start the service : Status 7 (7 : The service is paused.)`
Have you tried to restart your computer ?

**Comment by iansebryk** [comment]
yes.  in fact, it started AFTER i rebooted.  and now it continues: every reboot, logout/login, &c.  💩  i have neard scripted for a delayed start on startup/reboot/login and it has been working flawlessly since i last asked about the shutdown issue.  as of yesterday: poom!  no love.  😮  i checked Event Logs: nothing.  i checked my redists, they're okay.  so now:  just confused.  😕

**Comment by crazy-max** [comment]
Try this:

```
sc.exe queryex neardapache
taskkill /pid <SERVICE_PID> /f
```

Replace service pid with the pid returned by sc command

**Comment by iansebryk** [comment]
done.  no issues or errors.  now just restart the Apache service?

**Comment by iansebryk** [comment]
restarting ONLY the Apache service did nothing.  restarting all services popped up a simple dialog with 'Error starting the Apache service.'.  completely exiting Neard and restarting it regenerated the same error as before:  

![](https://user-images.githubusercontent.com/1943574/40524659-ee701f9a-5f98-11e8-9275-df3800dc48e4.jpg)

**Comment by crazy-max** [comment]
Close everything on your computer and test `sc delete neardapache`

**Comment by crazy-max** [comment]
Btw, can you type also `winver` and post the screenshot please. Thanks.

**Comment by iansebryk** [comment]
ok.  ran `sc delete neardapache` and... nothing.  which i presume is the right answer there. BUT, when i attempted to restart neard, i got this:

![neard-new-apache-error](https://user-images.githubusercontent.com/1943574/40569715-2c3d1a8c-6041-11e8-8bc6-519ae0aab967.jpg)

here's the (sanitized) screenshot of `winver`:

![neard-winver](https://user-images.githubusercontent.com/1943574/40569723-37673410-6041-11e8-9cb4-213eef72aae0.jpg)

since i'm kinda dead in the water, i've been digging like a mad ferret and found [this article](https://github.com/davenuman/bowline/issues/37).  i am going to give it a shot and look at my permissions, but could it be relevant?  i can't fathom why permissions would suddenly change, but, hell... this is a computer.  might as well dig out a knife, some candles, and a rabbit while i'm at it...

**Comment by iansebryk** [comment]
FFS.  the conflict is with VMWare Workstation Pro 14.  it is the *only* thing that has changed system-wise and i just ripped it out... everything is now green.  re-installed it: bork bork die.  what the seven levels of hell!?  does this make sense to you??  how do we work around this?  anyone else have a problem with VMWW and Neard?

**Comment by crazy-max** [comment]
Knock knock : https://github.com/neard/neard/issues/360#issuecomment-375690336 :sweat_smile:

**Comment by crazy-max** [comment]
Try this : https://superuser.com/questions/414717/trying-to-run-apache-but-vmware-workstation-is-blocking-port-80

**Comment by crazy-max** [comment]
Next time you can use [TCPView](https://docs.microsoft.com/fr-fr/sysinternals/downloads/tcpview) to find out which process uses TCP port

**Comment by crazy-max** [comment]
I will create an item in the FAQ for this issue

**Comment by iansebryk** [comment]
...i searched for 'paused service' and that article didn't come up.  ☹️  and given that i run VBox with no issue, it never entered my mind to even look at VMWare... i mean, bloody hell...  i feel like an utter idiot.  i tested port 80.  it was unused!   ffffuuu.....

**Comment by crazy-max** [comment]
Yes that's pretty weird :/

**Comment by crazy-max** [comment]
==> https://neard.io/doc/faq/#vmware-service-uses-port-80-and-443

**Comment by iansebryk** [comment]
ye gods!  how could i have missed all this so horribly??

**Comment by crazy-max** [comment]
No stress, it happens to everyone;)
