### ISSUE TITLE
can we ADD or MOVE tools in the tray menu?

### ISSUE THREAD

**Issue by iansebryk** [neard/neard#377]
i'd like to be able to move some tools out of their nested locations in the tray menu for speedier access.  is this doable?  if so, how?

as always, thanks for the amazing work you're doing, @crazy-max.  very much appreciated.  😃

**Comment by crazy-max** [comment]
@iansebryk Unfortunately no, i don't maintain [Aestan Tray Menu](https://neard.io/doc/faq/#where-is-the-source-code-of-neardexe-) :sweat_smile:

**Comment by iansebryk** [comment]
yeaaah...  :slap:  you're a patient man, @crazy-max ...  i'll go bug them...  😄
