### ISSUE TITLE
console prompt -> want to look at solution again

### ISSUE THREAD

**Issue by iansebryk** [neard/neard#378]
a while back i'd asked about changing the console prompt (because it's godawful.  sorry, but it is).  i thought we'd found a solution, but i can neither remember what it was nor does what i remember work.  so i was wondering if it could be dug up from the grave so i could look at it again?

for what its worth, i've been bashing (no pun) my head against this all day, and something Console does obliterates any .bashrc, bash_prompt.sh or .profile settings for the bash shell.  and there's zero docs on how to set the prompt for Console itself... i want to tear my eyes out...

**Comment by crazy-max** [comment]
@iansebryk If you have a console alternative or changes to propose, feel free to contribute and help us to make this module evolve.

**Comment by iansebryk** [comment]
hey @crazymax.  i am working on a possible fix for this locally.  i'm just buried under other work, so its slow going... (sound familiar?  lol).  thanks for your patience with my nitpickiness.  :P

**Comment by crazy-max** [comment]
@iansebryk Most FOSS projects owe their existence and progress to the involvement of the community. There's no hurry and I appreciate your dedication.

**Comment by crazy-max** [comment]
Closed in favor of #406
