### ISSUE TITLE
PhpMyAdmin cannot loggin to MySQL 8 

### ISSUE THREAD

**Issue by myspulin** [neard/neard#384]
Hi,

I have installed the new vesion of MySQL 8.0.11. Then I tried to log in to the phpmyadmin 4.8.2 which is the latest version. But I get these errors:

#2054 - The server requested authentication method unknown to the client

mysqli_real_connect(): The server requested authentication method unknown to the client [caching_sha2_password]

mysqli_real_connect(): (HY000/2054): The server requested authentication method unknown to the client

My OS is Windows 7 64-bits, Neard version is 1.4, PHP v7.1.12.

I have no problems with older version of MySQL 5.7.18. After switching back everything works perfectly.

I did some research of this error and there is a solution:

New MySQL 8.0.11 is using caching_sha2_password as default authentication method. I think that phpMyAdmin cannot understand this authentication method. You need to create user with one of the older authentication method, e.g. CREATE USER xyz@localhost IDENTIFIED WITH mysql_native_password BY 'passw0rd'

So could you please create the new user and update the package?

Thanks a lot, love this software so much!

Lukas

**Comment by crazy-max** [comment]
Hi @myspulin, thanks for this concise report, i keep you in touch

**Comment by myspulin** [comment]
Thanks, you are the best;-)

**Comment by N6REJ** [comment]
@crazy-max  just fyi, mysql 8 doesn't work with Joomla! either.  Thats not a neard issue.

**Comment by myspulin** [comment]
@crazy-max Hi, would you be please so kind and explain what does it mean does not work? Because this issue is about logging in to database through the PHPMyAdmin. So after the mysql 8 package download and install user is unable to log in. Thanks.

**Comment by crazy-max** [comment]
@myspulin @N6REJ Yes not related to this issue

**Comment by crazy-max** [comment]
Available : https://neard.io/modules/mysql/#releases

**Comment by N6REJ** [comment]
> @N6REJ Hi, would you be please so kind and explain what does it mean does not work? Because this issue is about logging in to database through the PHPMyAdmin. So after the mysql 8 package download and install user is unable to log in. Thanks.

Joomla 3.x and 4.x does not currently support mysql 8+ nor mariadb 10+

**Comment by ps374** [comment]
> 
> 
> Hi,
> 
> I have installed the new vesion of MySQL 8.0.11. Then I tried to log in to the phpmyadmin 4.8.2 which is the latest version. But I get these errors:
> 
> #2054 - The server requested authentication method unknown to the client
> 
> mysqli_real_connect(): The server requested authentication method unknown to the client [caching_sha2_password]
> 
> mysqli_real_connect(): (HY000/2054): The server requested authentication method unknown to the client
> 
> My OS is Windows 7 64-bits, Neard version is 1.4, PHP v7.1.12.
> 
> I have no problems with older version of MySQL 5.7.18. After switching back everything works perfectly.
> 
> I did some research of this error and there is a solution:
> 
> New MySQL 8.0.11 is using caching_sha2_password as default authentication method. I think that phpMyAdmin cannot understand this authentication method. You need to create user with one of the older authentication method, e.g. CREATE USER xyz@localhost IDENTIFIED WITH mysql_native_password BY 'passw0rd'
> 
> So could you please create the new user and update the package?
> 
> Thanks a lot, love this software so much!
> 
> Lukas

Hi @myspulin 
I had the same issue exactly and I tried several things to get it fixed but nothing worked (also reinstalled MySQL Server 8.0 with Legacy Authentication Method). Later, I downloaded phpMyAdmin 5.0 (Alpha) version (link: [)](https://files.phpmyadmin.net/phpMyAdmin/5.0.0-alpha1/phpMyAdmin-5.0.0-alpha1-all-languages.zip) then it worked quite smoothly. I do not see that error messages while logging in and I can see my databases listed there.

Hope it helps!
