### ISSUE TITLE
Le service Apache 2.4.29 (neardapache) ne peut être installé

### ISSUE THREAD

**Issue by berthos** [neard/neard#385]
La suite du message : impossible de démarrer le service : Erreur Statut 7 (7 : the service is paused)

Je viens d'installer la version 1.4 de Neard à partir du Zip sur un disque dur externe.
J'ai lancé Neard et j'ai eu le problème ci-dessous.
 J'ai essayé de regarder les logs d'apache mais il n'y a rien. Le port 80 est disponible.
Quand je regarde les services windows, le neard apache est en pause. Si j'essaie de le relancer, il se relance.

Mais le localhost est toujours inaccessible.
Dans l'interface neard, j'ai redémarré apache mais cela ne change rien

ci-dessous les logs demandés

[logs.zip](https://github.com/neard/neard/files/2336569/logs.zip)
[core.zip](https://github.com/neard/neard/files/2336570/core.zip)

My config est windows 10 Pro

**Comment by crazy-max** [comment]
Comme le disent les logs dans `neard-startup.log`, le service est en pause et ne peut donc être démarré :

```
[2018-08-30 16:01:37] # Neard 1.4 # DEBUG: Error: Le service Apache 2.4.29 (neardapache) ne peut être installé :
- Impossible de démarrer le service : Erreur Statut 7 (7 : The service is paused.)
```

* Quittez Neard
* Redémarrez votre ordinateur
* Vérifiez si le service `neardapache` est bien absent dans la liste des services Windows
* Démarrez Neard

Si il est toujours présent après redémarrage, exécutez la commande `sc delete neardapache` et vérifiez à nouveau.

**Comment by berthos** [comment]
J'ai changé de PC et je n'ai plus le problème et sur mon autre PC je n'ai pas non ce problème. Je ferme la question.

**Comment by berthos** [comment]
Je suis revenu sur mon ancien PC, et je m'interroge sur le problème même en redémarrant le PC et en relançant le neard apache (qui est en pause) il passe en cours d'exécution puis directement en pause.
