### ISSUE TITLE
issues with Joomla 4 alpha

### ISSUE THREAD

**Issue by N6REJ** [neard/neard#388]
Max, when you go to install J4 from git source it complains because it's not finding either npm or composer.  I believe its composer.
If I open a git bash terminal in the joomla folder it finds npm but not composer, if I open a composer terminal from neard then ofc composer is found.
windows cmd does see composer and npm just fine.  Is there something in neard that needs to be adjusted?  Why the ambiguity?

**Comment by N6REJ** [comment]
Max I think I see why things aren't working... if you do a `npm config ls -l` you'll see several path issues like these 
![image](https://user-images.githubusercontent.com/1850089/45520996-a57e9280-b781-11e8-8c19-90d4f4a8ced5.png)

Checking $path I see that everything looks fine ( carriage returns added for visual clarity )
[path.txt](https://github.com/neard/neard/files/2381335/path.txt)

I had installed browser-release but even completely replacing node didn't 100% fix the issue as seen here
![image](https://user-images.githubusercontent.com/1850089/45521825-69e5c780-b785-11e8-9e0a-566e4efee076.png)

Since this is turning into a "issue" I'm including the support files requested... 
os: win 10 x64 pro
neard: 1.4 ( with updates )

[tmp.zip](https://github.com/neard/neard/files/2381383/tmp.zip)
[logs.zip](https://github.com/neard/neard/files/2381384/logs.zip)

**Comment by N6REJ** [comment]
@crazy-max any work on fixing this so that npm will run properly?

**Comment by N6REJ** [comment]
@crazy-max node 10.11.0 worked MUCH better.. not sure if things are 100% fixed as I'm not a node expert.
[2018-10-03T20_14_57_770Z-debug.log](https://github.com/neard/neard/files/2443673/2018-10-03T20_14_57_770Z-debug.log)

**Comment by crazy-max** [comment]
@N6REJ Paths are ok on a clean install of Neard 1.4 with node 8.12.0 on my virtual machine. You should ask for help to the Joomla community : https://github.com/joomla/joomla-cms

**Comment by N6REJ** [comment]
might be a change between 8.9 and 8.12, if you look it up on google its a common problem.
