### ISSUE TITLE
php and phpmyadmin require an updated version.

### ISSUE THREAD

**Issue by ziselive** [neard/neard#393]
hi, @crazy-max 
php and phpmyadmin require an updated version.
php7.2.8 and phpmysql4.7.0 version, import database error.

Warning in .\libraries\plugin_interface.lib.php#551
count(): Parameter must be an array or an object that implements Countable

The latest version of phpmyadmin(4.8.3) is normal.

**Comment by crazy-max** [comment]
Hi @ziselive, check the latest release pack : https://neard.io/modules/phpmyadmin/#releases
