### ISSUE TITLE
Replace Console with ConsoleZ

### ISSUE THREAD

**Issue by hennell-git** [neard/neard#406]
Due to display issues Console looks very 'blurry' on my screens which ends up giving me a headache. I found a more updated fork of console called [ConsoleZ](https://github.com/cbucher/console), which displays much nicer (and has font ligatures, split screens and other cool features)

I've actually been using ConsoleZ with neard for months without issue (tried wiring it up with the conf files, but found simply renaming the exe and replacing the original console.exe worked fine for my needs), so figure it might be worth moving to it for an official package?

(It looks like this was proposed in #42, but rejected for TCC reasons. With #288 replacing TCC with clink, and the fact my low-effort rename-replace solution seems to work ;) I think it might be worth a re-look?)

**Comment by crazy-max** [comment]
Hi @hennell-git, looks like a good idea now :upside_down_face:. I put this in my backlog thanks :)

**Comment by iansebryk** [comment]
this is the best news i've heard all day.  i didn't even know ConsoleZ existed and this lets @crazy-max close the door on my [whinging] (https://www.thefreedictionary.com/whinging) about the console...  lol  ;)  awesome-sauce.

**Comment by crazy-max** [comment]
@iansebryk Sorry if I was a little too hard ahah :innocent:

**Comment by iansebryk** [comment]
not at all!  you're awesome!   i just felt bad that my stupid OCD had you worrying about something as low-priority as the console...  and i'm thrilled that @hennel-git found a fix that fixes that.  :)

**Comment by crazy-max** [comment]
@hennell-git @iansebryk Added in [v1.6.3](https://github.com/neard/neard/releases/tag/v1.6.3) for testing

**Comment by crazy-max** [comment]
@hennell-git @iansebryk Available through [1.7 release](https://neard.io/release/1.7/).
