### ISSUE TITLE
Mysql error on export

### ISSUE THREAD

**Issue by N6REJ** [neard/neard#421]
Windows 10 x64 pro.
Neard 1.6
phpmyadmin: "C:\\neard\\apps\\phpmyadmin\\phpmyadmin4p7\\4.8.3\\vendor\\composer/../tecnickcom/tcpdf/tcpdf.php'"

Getting a massive error when trying to export a db.
![image](https://user-images.githubusercontent.com/1850089/63900938-23a26c00-c9c8-11e9-9035-c6c87f7b6db4.png)
[neard-mysql-error.zip](https://github.com/neard/neard/files/3553334/neard-mysql-error.zip)

**Comment by crazy-max** [comment]
Looks like an issue linked to phpmyadmin/phpmyadmin#15384. As it is a Warning you can ignore this and continue. We will wait until this is fixed on the phpMyAdmin side to provide a new package.

**Comment by N6REJ** [comment]
@crazy-max just an fyi, applying does infact solve the issue.
https://github.com/tecnickcom/TCPDF/pull/91

**Comment by crazy-max** [comment]
@N6REJ Ok thx for your feedback

**Comment by N6REJ** [comment]
just an fyi, tcpdf just told me its been fixed for a long time and that current is https://github.com/tecnickcom/TCPDF/releases/tag/6.2.26
So, perhaps you need to poke phpmyadmin?  idk.. your rice bowl now :D
