### ISSUE TITLE
Checksums generate 404 errors on neard.io latest release page

### ISSUE THREAD

**Issue by celtic-coder** [neard/neard#424]
Hi @crazy-max,

The checksums on both the [Latest Release](https://neard.io/release/latest/) and the [1.6 Release](https://neard.io/release/1.6/) pages on **neard.io** - since they are basically the same page - generate a 404 error. 

For example, the [MD5](https://neard.io/download/neard-1.6.7z.md5/) verification redirects to [https://github.com/neard/neard/releases/download/v1.6/neard-1.6.7z/.md5](https://github.com/neard/neard/releases/download/v1.6/neard-1.6.7z/.md5), which is invalid.

In contrast, the [v1.6 Release page](https://github.com/neard/neard/releases/tag/v1.6) on **GitHub** has the correct verification links.. The **MD5** link goes to [https://github.com/neard/neard/releases/download/v1.6/neard-1.6.7z.md5](https://github.com/neard/neard/releases/download/v1.6/neard-1.6.7z.md5), which is correct. 

Notice the extra forward slash between the "7z" and the ".md5" ([7z/.md5](7z/.md5)) in the incorrect link. The same is also true of the three SHA verification checksums on the **neard.io**  pages.

Kind Regards,
Liam

**Comment by crazy-max** [comment]
Hi @celtic-coder,

Thanks for your report, this is now fixed.
