### ISSUE TITLE
Running Neard from mapped drive

### ISSUE THREAD

**Issue by Dean-kasail** [neard/neard#425]
Windows 7 64-bits
Neard version :1.6

I am trying to run neard from a networked drive but it gives me a Silent vbs error, i believe its due to using the path //web-dev/neard instead of C:/neard

is there some settings i can change to get this going as it would be beneficial for me to keep my files on the network as it is fully backup

**Comment by crazy-max** [comment]
@Dean-kasail Network drives are not supported.

**Comment by N6REJ** [comment]
if you search closed issues there is one I made a couple of years back that states alot of whats required.
I bet if you created a hard symbolic link i.e f: -> c:\neard it would function.
I've done it but as I recall I had to write a batch file to do so.
