### ISSUE TITLE
Access apache from droid 

### ISSUE THREAD

**Issue by N6REJ** [neard/neard#426]
Hey max, 
Whats the exact purpose/function of putting neard online?  I THOUGHT it was to allow other network devices access but apparently not.  I had to create a rule in windows 10 firewall for "private" to allow port 80 from the 192.168.1.0/24 class c to get it to work.

**Comment by crazy-max** [comment]
Hi @N6REJ,

> Whats the exact purpose/function of putting neard online?

To use it through your network

> I had to create a rule in windows 10 firewall

That's quite normal if you have a firewall on your computer

**Comment by N6REJ** [comment]
ok, ty max, I would've thought neard triggered it when it first triggered apache but I guess not.  Maybe you could document how its done cause it took me a while to figure out how as win 10 likes to over simplify everything so that makes it difficult to find the real "power" to get things done.

**Comment by crazy-max** [comment]
I think the Windows Firewall is not triggered anymore on Windows 10
