### ISSUE TITLE
phpcs doesn't function

### ISSUE THREAD

**Issue by N6REJ** [neard/neard#434]
Max, having an issue with phpstorm where it's throwing the following error...
`phpcs: '"@php_bin@"' is not recognized as an internal or external command`
any clue where to get started looking?

**Comment by crazy-max** [comment]
https://lmgtfy.com/?q=phpcs%3A+%27%22%40php_bin%40%22%27+is+not+recognized+as+an+internal+or+external+command

**Comment by N6REJ** [comment]
btdt, HOWEVER I would expect that since neard sets the php pathing it's a neard pathing issue, ergo my ticket.
