### ISSUE TITLE
mysql 5.7.xx error during startup

### ISSUE THREAD

**Issue by N6REJ** [neard/neard#438]
Anyone but me receive this notice on startup with using mysql 5.7.18?
![image](https://user-images.githubusercontent.com/1850089/71561211-24601300-2a39-11ea-88a6-d7bf8bbb218b.png)
interesting part is, it works fine after clicking 'ok'

OS: Win 10 x64 pro
neard: 1.6 with all the latest updates ( including changing mysql to latest 5.x )
neard state: online active.

[bear.zip](https://github.com/neard/neard/files/4008430/bear.zip)

**Comment by N6REJ** [comment]
@crazy-max any chance this will get addressed soon?

**Comment by N6REJ** [comment]
5.7.26 doesn't have this issue

**Comment by N6REJ** [comment]
actually, after migrating the database it did show up.  So it's most likely a config issue.

**Comment by crazy-max** [comment]
@N6REJ Looks like a timeout issue while starting database.

**Comment by crazy-max** [comment]
Fixed in 1.6.1
