### ISSUE TITLE
updating mysql from 5.7.18 to 5.7.26 fails to copy data

### ISSUE THREAD

**Issue by N6REJ** [neard/neard#439]
upgraded from 5.7.18 to 5.7.26 and after selecting 5.7.26 and restarting neard it said it was updating the data.  On next restart i get the following error when trying to access my test joomla sites...
`
Warning: session_start(): Failed to initialize storage module: user (path: D:/Development/neard/tmp) in D:\Development\neard\www\j4\libraries\vendor\joomla\session\src\Storage\NativeStorage.php on line 478
Error: Failed to start the session because headers have already been sent by "D:\Development\neard\www\j4\libraries\vendor\joomla\session\src\Storage\NativeStorage.php" at line 478.: Could not connect to database: Access denied for user 'joomla'@'localhost' (using password: YES)`

**Comment by crazy-max** [comment]
Please create a proper bug report: https://neard.io/doc/reporting-issue/
