### ISSUE TITLE
Error after update PHP 7.4.4

### ISSUE THREAD

**Issue by berthos** [neard/neard#441]
Hi
First here is my config 
Apache : 2.4.39
OpenSSL : 1.0.2r
PHP : 7.4.4
phpMyAdmin : 4.8.3
MySQL : 8.0.16
Mailhog : 1.0.0
Windows 10 1903

Strangely after doing the update of PHP 7.4.4 (from PHP 7.3.5).

Each time I display a table in PHPMyAdmin, longs errors messages appears. See the messages below and also the attached files (https://www.sendspace.com/filegroup/30uebMZv%2BRFvYYAoTXR9dw).

Deprecation Notice in .\libraries\classes\DatabaseInterface.php#578
 Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)`

Backtrace

.\vendor\composer\ClassLoader.php#444: include()
.\vendor\composer\ClassLoader.php#322: Composer\Autoload\includeFile(string 'D:\\Dropbox\\Dropbox\\_Stephane\\Web\\neard\\apps\\phpmyadmin\\phpmyadmin4p7\\4.8.3\\vendor\\composer/../../libraries/classes\\DatabaseInterface.php')
Composer\Autoload\ClassLoader->loadClass(string 'PhpMyAdmin\\DatabaseInterface')
.\libraries\common.inc.php#314: spl_autoload_call(string 'PhpMyAdmin\\DatabaseInterface')
.\sql.php#20: require_once(.\libraries\common.inc.php)
Deprecation Notice in .\libraries\classes\Url.php#251
 Array and string offset access syntax with curly braces is deprecated

Backtrace

.\vendor\composer\ClassLoader.php#444: include()
.\vendor\composer\ClassLoader.php#322: Composer\Autoload\includeFile(string 'D:\\Dropbox\\Dropbox\\_Stephane\\Web\\neard\\apps\\phpmyadmin\\phpmyadmin4p7\\4.8.3\\vendor\\composer/../../libraries/classes\\Url.php')
Composer\Autoload\ClassLoader->loadClass(string 'PhpMyAdmin\\Url')
.\libraries\classes\Header.php#231: spl_autoload_call(string 'PhpMyAdmin\\Url')
.\libraries\classes\Header.php#282: PhpMyAdmin\Header->getJsParams()
.\libraries\classes\Header.php#214: PhpMyAdmin\Header->getJsParamsCode()
.\libraries\classes\Header.php#142: PhpMyAdmin\Header->_addDefaultScripts()
.\libraries\classes\Response.php#100: PhpMyAdmin\Header->__construct()
.\libraries\classes\Response.php#134: PhpMyAdmin\Response->__construct()
.\libraries\common.inc.php#428: PhpMyAdmin\Response::getInstance()
.\sql.php#20: require_once(.\libraries\common.inc.php)
Notice in .\libraries\classes\Display\Results.php#1210
 Trying to access array offset on value of type bool

Backtrace

.\libraries\classes\Display\Results.php#1328: PhpMyAdmin\Display\Results->_getTableHeadersForColumns(
array,
array,
array,
array,
array,
boolean false,
string 'SELECT * FROM `ou` ',
)
.\libraries\classes\Display\Results.php#4279: PhpMyAdmin\Display\Results->_getTableHeaders(
array,
array,
string 'SELECT * FROM `ou` ',
array,
array,
array,
boolean false,
)
.\libraries\classes\Sql.php#1735: PhpMyAdmin\Display\Results->getTable(
,
array,
array,
boolean false,
)
.\libraries\classes\Sql.php#2031: PhpMyAdmin\Sql->getHtmlForSqlQueryResultsTable(
,
string './themes/metro/img/',
NULL,
array,
boolean true,
string '28',
integer 25,
NULL,
,
array,
)
.\libraries\classes\Sql.php#2252: PhpMyAdmin\Sql->getQueryResponseForResultsReturned(
,
array,
string 'aleph2at',
string 'ou',
NULL,
NULL,
,
string './themes/metro/img/',
string '28',
integer 25,
NULL,
NULL,
NULL,
NULL,
NULL,
string 'SELECT * FROM `ou` ORDER BY `ou`.`Id` DESC',
NULL,
)
.\libraries\classes\Sql.php#2112: PhpMyAdmin\Sql->executeQueryAndGetQueryResponse(
array,
boolean true,
string 'aleph2at',
string 'ou',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/metro/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `ou` ORDER BY `ou`.`Id` DESC',
NULL,
NULL,
)
.\sql.php#215: PhpMyAdmin\Sql->executeQueryAndSendQueryResponse(
array,
boolean true,
string 'aleph2at',
string 'ou',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/metro/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `ou` ORDER BY `ou`.`Id` DESC',
NULL,
NULL,
)

**Comment by crazy-max** [comment]
Upgrade to phpMyAdmin 4p8 module

**Comment by berthos** [comment]
Hi,
I have installed phpMyAdmin 4p8 module and no more error messages. 

Thanks a lot

By the way, I have reinstalled the theme metro for phpmyadmin : https://www.phpmyadmin.net/themes/#pma_4_9
it is good
