### ISSUE TITLE
PHPMyAdmin : Error while displaying a field of the structure of a table

### ISSUE THREAD

**Issue by berthos** [neard/neard#442]
Hi,

When I open the modification screen for a field in PHPMyAdmin, an error occurs :

https://www.sendspace.com/file/aex6e6

Here is the error message 
{`
Deprecation Notice in .\libraries\tbl_columns_definition_form.inc.php#431
Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)`

Backtrace

.\libraries\classes\Controllers\Table\TableStructureController.php#552: include()
.\libraries\classes\Controllers\Table\TableStructureController.php#1492: PhpMyAdmin\Controllers\Table\TableStructureController->displayHtmlForColumnChange(
array,
string 'tbl_structure.php',
)
.\libraries\classes\Controllers\Table\TableStructureController.php#239: PhpMyAdmin\Controllers\Table\TableStructureController->getDataForSubmitMult(
string 'change',
array,
string 'tbl_structure.php',
)
.\tbl_structure.php#57: PhpMyAdmin\Controllers\Table\TableStructureController->indexAction()

`}

My dev context :
Apache : 2.4.39
OpenSSL : 1.0.2r
PHP : 7.4.4
phpMyAdmin : 4.9.1
MySQL : 8.0.16
Mailhog : 1.0.0
NodeJS : 13.2.0
Windows 10 1903
GIT : 2.20.1

**Comment by crazy-max** [comment]
@berthos Please edit your issue and put code and/or error messages in [Fenced Code Blocks](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks).

**Comment by berthos** [comment]
Hi
I have already the higher version of PHPMyAdmin 4.9.1

My dev context :
Apache : 2.4.39
OpenSSL : 1.0.2r
PHP : 7.4.4
phpMyAdmin : 4.9.1
MySQL : 8.0.16
Mailhog : 1.0.0
NodeJS : 13.2.0
Windows 10 1903
GIT : 2.20.1

**Comment by crazy-max** [comment]
@berthos I said we just need to upgrade phpMyAdmin module as this issue is [fixed in phpMyAdmin 4.9.2](https://github.com/phpmyadmin/phpmyadmin/issues/15499).

**Comment by crazy-max** [comment]
@berthos New module available: Available : http://neard.io/modules/phpmyadmin/#releases
