### ISSUE TITLE
Apache fails to start on php version change

### ISSUE THREAD

**Issue by N6REJ** [neard/neard#448]
#### Steps to reproduce this issue
1. change php version to php 5.xx
2. neard changes php version but fails to start apache.
3. go to apache service and hit "start service"
4. apache fails to start.
5. stop all services. then start all services.
6. apache will throw error below if went from php 7 to php5
![image](https://user-images.githubusercontent.com/1850089/78613998-ea21c100-7832-11ea-878c-718dce883a10.png)
or 
![image](https://user-images.githubusercontent.com/1850089/78613689-17ba3a80-7832-11ea-8b3c-1093316e195f.png)
if going from php 5 to php 7.
hit "ok" after lots of processing apache still fails to start.
5. exit neard and restart.
6. Neard will start as normal.

#### Expected behaviour
switches version and reloads apache as in prior versions.

### Configuration

* Neard version and the previous version in case of upgrade: 
previous: 1.6
current: 1.7
* Operating system: 
win 10 x64 pro

### Logs
[logs.zip](https://github.com/neard/neard/files/4441247/logs.zip)

**Comment by crazy-max** [comment]
@N6REJ Thanks for your report.

**Comment by N6REJ** [comment]
update: switching apache versions instead of restarting neard causes apache to load properly.

**Comment by crazy-max** [comment]
@N6REJ Fixed in 1.7.1
