### ISSUE TITLE
PostgreSQL fails to start

### ISSUE THREAD

**Issue by iansebryk** [neard/neard#449]
#### Steps to reproduce this issue

start neard.

#### Expected behaviour

on startup, neard should load postgresql.

#### Actual behaviour

on startup, neard generates this error:
![neard-postgre-startup-error](https://user-images.githubusercontent.com/1943574/78828717-5ec73d80-79a2-11ea-97b2-cb375de52b12.jpg)

### Configuration

neard 1.7.1  (hasn't worked since 1.5, but i hadn't needed it until now, so i didn't care...)

### Logs

[postgresql-startup-error.zip](https://github.com/neard/neard/files/4452599/postgresql-startup-error.zip)

**Comment by crazy-max** [comment]
@iansebryk Cannot reproduce on Windows 10. Have you installed the latest [Neard Prerequisites Package](https://github.com/neard/prerequisites/releases/latest)? If so, can you try with [PostgresSQL 9.6.13](https://neard.io/download/neard-postgresql-9.6.13-r4.7z/)?

**Comment by iansebryk** [comment]
ok.  i installed the updated prereqs... now everything is broken.  :D  yay.  here's what is happening now:

![neard-postgre-new-error-00](https://user-images.githubusercontent.com/1943574/79162861-3a50d400-7d9b-11ea-84e5-b93309e4ea65.jpg)

and a fresh set of logs and tmp:

[postgresql-startup-new-errors.zip](https://github.com/neard/neard/files/4471946/postgresql-startup-new-errors.zip)

so as of now, i'm dead in the water.  :P

**Comment by crazy-max** [comment]
@iansebryk Neard Prerequisites Package only installs the [Visual C++ Redistributables](https://github.com/neard/prerequisites#visual-c-redistributables) so nothing should change. I suspect something else on your computer. Can you download and unzip Neard in a fresh new location and try from this one?
Also your logs does not seem to have `logsVerbose` variable to the value `2` in the `neard.conf` file.

**Comment by iansebryk** [comment]
frick.  forgot to save that.  i'll redo.  for what it's worth, it was running okay, *literally*, during the install of the prereqs.  then i quit and restarted neard and *kaboooom*.  but.  stranger shit has happened on this machine, so i'm not averse to reinstalling.  as long as it gets me back up and running.  thanks for the quick response Max.

**Comment by iansebryk** [comment]
okay.  flag properly set, fresh logs, fresh tmp.  same error.  also going to reinstall after this post in a new location and give it whirl from there (thanks to the beauty of neard itself!)

the corrected zip:

[postgresql-startup-new-errors-properly.zip](https://github.com/neard/neard/files/4472039/postgresql-startup-new-errors-properly.zip)

**Comment by iansebryk** [comment]
well.  tried brand new install... nothing works.  doesn't even fire up.  the tray icon shows up and that's it.  most of the processes are in the task manager, but there's no loading sequence as per usual.  also, there are no menus available from the tray icon.  😕 restarted the system and still.  no love.  install is totally borked.  not sure what to do from here... i literally only changed the postgre flag from 0 to 1 at the start of this all...  *sigh*

**Comment by crazy-max** [comment]
@iansebryk,

Looking at the logs Neard seems to be running already:

```
[2020-04-13 15:39:38] # Neard 1.7.1 # DEBUG: -> neard.exe (PID 10632) in C:/neard/neard.exe
[2020-04-13 15:39:38] # Neard 1.7.1 # DEBUG: -> neard.exe (PID 16192) in C:/neard/neard.exe
```
> `neard-startup.log`

Also, your system path seems corrupted with other paths that could interfere with your current installation:

```
[2020-04-13 15:39:46] # Neard 1.7.1 # DEBUG: Refresh system PATH: %NEARD_BINS%;C:\Program Files\Python35\Scripts\;C:\Program Files\Python35\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\neard\bin\apache\apache2.4.29\bin;C:\neard\bin\php\php7.2.13;C:\neard\bin\php\php7.2.13\pear;C:\neard\bin\php\php7.2.13\deps;C:\neard\bin\php\php7.2.13\imagick;C:\neard\bin\nodejs\nodejs11.4.0;C:\neard\tools\composer\composer1.5.6;C:\neard\tools\composer\composer1.5.6\vendor\bin;C:\neard\tools\drush\drush8.1.15;C:\neard\tools\ghostscript\ghostscript9.22\bin;C:\neard\tools\git\git2.19.1\bin;C:\neard\tools\ngrok\ngrok2.2.8;C:\neard\tools\perl\perl5.26.0.1\perl\site\bin;C:\neard\tools\perl\perl5.26.0.1\perl\bin;C:\neard\tools\perl\perl5.26.0.1\c\bin;C:\neard\tools\phpmetrics\phpmetrics1.9.2;C:\neard\tools\phpunit\phpunit6.5.5;C:\neard\tools\python\python3.6.6.2\bin;C:\neard\tools\ruby\ruby2.4.4-2\bin;C:\neard\tools\wpcli\wpcli0.24.1;C:\neard\tools\yarn\yarn1.12.3;C:\neard\tools\yarn\yarn1.12.3\global\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\neard\bin\apache\apache2.4.29\bin;C:\neard\bin\php\php7.2.13;C:\neard\bin\php\php7.2.13\pear;C:\neard\bin\php\php7.2.13\deps;C:\neard\bin\php\php7.2.13\imagick;C:\neard\bin\nodejs\nodejs11.4.0;C:\neard\tools\composer\composer1.5.6;C:\neard\tools\composer\composer1.5.6\vendor\bin;C:\neard\tools\drush\drush8.1.15;C:\neard\tools\ghostscript\ghostscript9.22\bin;C:\neard\tools\git\git2.19.1\bin;C:\neard\tools\ngrok\ngrok2.2.8;C:\neard\tools\perl\perl5.26.0.1\perl\site\bin;C:\neard\tools\perl\perl5.26.0.1\perl\bin;C:\neard\tools\perl\perl5.26.0.1\c\bin;C:\neard\tools\phpmetrics\phpmetrics1.9.2;C:\neard\tools\phpunit\phpunit6.5.5;C:\neard\tools\python\python3.6.6.2\bin;C:\neard\tools\ruby\ruby2.4.4-2\bin;C:\neard\tools\wpcli\wpcli0.24.1;C:\neard\tools\yarn\yarn1.12.3;C:\neard\tools\yarn\yarn1.12.3\global\bin;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Extensis\Suitcase Fusion\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\QuickTime Alternative\QTSystem
```
> `neard-startup.log`

Remove everything starting with `c:\neard` in your system path (already handled by `%NEARD_BINS%`):

```
%NEARD_BINS%;C:\Program Files\Python35\Scripts\;C:\Program Files\Python35\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Extensis\Suitcase Fusion\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\QuickTime Alternative\QTSystem
```

**Comment by iansebryk** [comment]
okay.  knowing that Windoze is like a retarded teenager and can't clean up after itself, i took a peek at the registry and did a big clean and rework.  upside: everything is working as before, downside: Postgre is still borked.  i followed your advice and cleaned out the extra paths from the system path (wow, those have been there since the beginning!) and still, Postgre doesn't start.  here's the fresh logs.  first set of entries was pre-path clean, the second, post-path clean.  i'm not stressing too much since i'm back up and running, but i am concerned that i can't get Postgre running, which i need next week.  :P  probably should note that since cleaning out the path, NONE of the consoles work and i can't directly go to any of the .ini files... 

![neard-ini-error](https://user-images.githubusercontent.com/1943574/79270325-32586900-7e5b-11ea-9cff-b2db6a6a04c8.jpg)


thank you for your patient attention to this.  very much appreciated.

[postgre-failure-pre-and-post-path-clean.zip](https://github.com/neard/neard/files/4473674/postgre-failure-pre-and-post-path-clean.zip)

**Comment by crazy-max** [comment]
@iansebryk 

> did a big clean and rework.

A little too much, there is only `%NEARD_BINS%` now in your system PATH:

```
[2020-04-14 01:03:24] # Neard 1.7.1 # DEBUG: Current system PATH: %NEARD_BINS%;
[2020-04-14 01:03:24] # Neard 1.7.1 # DEBUG: New system PATH: %NEARD_BINS%;
[2020-04-14 01:03:24] # Neard 1.7.1 # DEBUG: Refresh system PATH: %NEARD_BINS%;
```

Put this instead:

```
%NEARD_BINS%;C:\Program Files\Python35\Scripts\;C:\Program Files\Python35\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Extensis\Suitcase Fusion\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\QuickTime Alternative\QTSystem
```

> i don't know if the .ini issues are ConsoleZ related or not. they worked fine with just Console in v1.6

Console is not compatible with Neard 1.7+ and [has been archived](https://github.com/neard/module-console). You have to switch to [ConsoleZ](https://neard.io/modules/consolez/).

> i can't get Postgre running

Ok back to square one. Can you follow those steps:

* Stop Neard
* Open [Rapid Environment Editor](https://www.rapidee.com/) as administrator and do File > Backup and post the reg file here (zipped).
* Next, remove `%NEARD_BINS%` from system PATH environment variable.
* Download and install [PostgreSQL for Windows](https://www.enterprisedb.com/thank-you-downloading-postgresql?cid=55) and tell me if it works.

> thank you for your patient attention to this. very much appreciated.

:+1:

**Comment by iansebryk** [comment]
ok.  when i alter the System Path as per above. the whole thing borks (see second error image).  when i remove it all, it still borks, but a reboot fixes that...sorta.  i get a 'Port 80 is in use by another application' error, but still get green lights on the tray app... (#hauntedComputer).  here's the backup from RPE of settings that work:

[backup_200414_170920.zip](https://github.com/neard/neard/files/4478317/backup_200414_170920.zip)

i have a notion that something odd is going on (duh).  this is Win10 after all and, given what i do for a living, i am asking it to do a lot of really weird stuff (because you have to if you typically work in Linux and want Windoze to do anything smart...).  i'll spin up a virgin instance of Win10 and try this out to see if it's just my configuration or base Win10 idiocy... back in a bit.

**Comment by iansebryk** [comment]
nope.  some kind of path fumbuckery.  here's the borked backup:

[backup_200414_175653.zip](https://github.com/neard/neard/files/4478341/backup_200414_175653.zip)

**Comment by iansebryk** [comment]
okay.  here's the new error:

![neard-modified-path-error](https://user-images.githubusercontent.com/1943574/79285283-59726300-7e7a-11ea-83b8-8d54f8928291.jpg)

and RPE backup to match:

[backup_200414_180307.zip](https://github.com/neard/neard/files/4478354/backup_200414_180307.zip)

sidenote:  i prefer using [Eveditor](https://eveditor.com), but i'll keep playing with RPE to see if i like it.

**Comment by iansebryk** [comment]
ok.  RPE is a nifty, nifty tool.  looks like the path `C:\neard\tools\composer\current\vendor\bin` fails because `...\currrent\` is a symlink that doesn't resolve to that path; it resolves to `C:\neard\tools\composer\composer1.9.1`.  same scenario with `C:\neard\tools\yarn\current\global\bin`. don't know how to fix this... this is a *FRESH* install.  the only changes were zeroing out the mongodb (because it's useless and stupid) and SVN (because i don't use it).

**Comment by iansebryk** [comment]
installed PostgreSQL 12.  works.  but it completely borks the neard app, even with postgre disabled in conf.  so i uninstalled it, restarted, and everything went back to baseline.  at this point my brain hurts and i've got to get back to work on the remainder of my current work.  i'll look at this again after Thursday.  thanks Max.  you're a champ, bud.

**Comment by crazy-max** [comment]
> 
> 
> ok. RPE is a nifty, nifty tool. looks like the path `C:\neard\tools\composer\current\vendor\bin` fails because `...\currrent\` is a symlink that doesn't resolve to that path; it resolves to `C:\neard\tools\composer\composer1.9.1`. same scenario with `C:\neard\tools\yarn\current\global\bin`. don't know how to fix this... this is a _FRESH_ install. the only changes were zeroing out the mongodb (because it's useless and stupid), Filezilla (don't need it) and SVN (because i don't use it).

That's not issue, those paths are pre-defined to handle global dependencies used by yarn or composer. For example if you want to use phpmd command globally on your computer you juste have to use `composer global require phpmd/phpmd` and it will be available in your PATH.

**Comment by crazy-max** [comment]
> i'll look at this again after Thursday.

Ok closing for now. Keep me in touch.

**Comment by N6REJ** [comment]
@crazy-max if he's got neard in c:\ doesn't it need admin privileges?  could this be the root cause?
I'm on win10 as you know and have none of these issues.

**Comment by iansebryk** [comment]
okay.  i've got both time and need to get this resolved.  new project is specced for PostgreSQL, so i'd need to get it running.  i just downloaded the new version of neard (1.8.0) and ran it fresh with the only config changes being the timezone and the browser path... and it dies.  won't load PostgreSQL.  :(

so.  here's the error and the logs/tmp files:

![Neard-1 8 0-PostgreSQL-startup-fail](https://user-images.githubusercontent.com/1943574/86180490-7fa6b700-bae9-11ea-812f-9b015677a1cb.jpg)

[Neard-1.8.0-PostgreSQL-startup-fail.zip](https://github.com/neard/neard/files/4854590/Neard-1.8.0-PostgreSQL-startup-fail.zip)

**Comment by N6REJ** [comment]
where is it located?  Do you have it running with admin privileges?

**Comment by iansebryk** [comment]
C:\neard  and it only runs with admin privileges, so, yes.  i had them.  always has.

**Comment by iansebryk** [comment]
shamelessly bumping  this because i need this to work. sorry, but i've been busy.

**Comment by iansebryk** [comment]
this is marked as 'needs more information'.  what do you need, my good man?  :)

**Comment by iansebryk** [comment]
whoops.  😝 here ya go.  fixed timezime accordingly.  still borks.  💩 

[PostgreSQL-Startup-Error-Logs-and-CoreTmp.zip](https://github.com/neard/neard/files/4928380/PostgreSQL-Startup-Error-Logs-and-CoreTmp.zip)

**Comment by rancoud** [comment]
> whoops. 😝 here ya go. fixed timezime accordingly. still borks. 💩
> 
> [PostgreSQL-Startup-Error-Logs-and-CoreTmp.zip](https://github.com/neard/neard/files/4928380/PostgreSQL-Startup-Error-Logs-and-CoreTmp.zip)

I run correctly PostgreSQL 11.3 with no problem on my computer on neard 1.8.0
I do all my unit tests with neard for https://github.com/rancoud/database

**Comment by weklost** [comment]
> 
> 
> > whoops. 😝 here ya go. fixed timezime accordingly. still borks. 💩
> > [PostgreSQL-Startup-Error-Logs-and-CoreTmp.zip](https://github.com/neard/neard/files/4928380/PostgreSQL-Startup-Error-Logs-and-CoreTmp.zip)
> 
> I run correctly PostgreSQL 11.3 with no problem on my computer on neard 1.8.0
> I do all my unit tests with neard for https://github.com/rancoud/database

It works well for me too on Windows 10 64-bits 19042.388.

@iansebryk I think you have a program that impinges on the workings of PostgreSQL

**Comment by crazy-max** [comment]
@iansebryk Can you give me the output of the command `systeminfo`?

**Comment by iansebryk** [comment]
here you go:
[systeminfo-eventLogs.zip](https://github.com/neard/neard/files/4967705/systeminfo-eventLogs.zip)

**Comment by crazy-max** [comment]
@iansebryk 

> @iansebryk Can you give me the output of the command systeminfo?

**Comment by crazy-max** [comment]
@iansebryk Your events logs has been cleared so I can't find anything relevant. Can you reproduce your issue and also export the Application and System event logs as evtx format please? Thanks.

**Comment by iansebryk** [comment]
oops.  looks like the redaction algo got a little greedy.  here's another set:
[systeminfo-eventLogs.zip](https://github.com/neard/neard/files/4968180/systeminfo-eventLogs.zip)

**Comment by iansebryk** [comment]
oops.  redaction algo got a little greedy.  here's another set in the requested format:
[systeminfo-eventLogs-evtx.zip](https://github.com/neard/neard/files/4968197/systeminfo-eventLogs-evtx.zip)
