### ISSUE TITLE
sorry not a bug.  stuck with Mailhog.  :(

### ISSUE THREAD

**Issue by iansebryk** [neard/neard#451]
find myself needing to use Mailhog to test email capabilities.  don't know how to configure it in the neard context.  using PHPMailer, i've set the SMTP port to 1025, but Mailhog isn't capturing anything.  i appreciate this might not be that place to ask, but i don't know where else i can go. stackoverflow has nothing (here's [my post there](https://stackoverflow.com/questions/61220173/phpmailer-mailhog-connection-refused-host-not-known)) and the mailhog docs are sparse as hell.  apologies in advance, but i need help.  feel free to redirect me as is fitting and delete this as necessary.  TIA.

**Comment by crazy-max** [comment]
@iansebryk Mailhog is enabled on port 25 not 1025:

![image](https://user-images.githubusercontent.com/1951866/79395274-8ce7e700-7f79-11ea-91b0-3073c8d3150e.png)

Small test using built-in mail function with this code in `C:\neard\www\mailhog.php`:

```php
<?php

$to = 'recipients@email-address.com';
$subject = 'Hello from Neard!';
$message = 'This is a Mailhog test';
$headers = "From: your@email-address.com\r\n";
if (mail($to, $subject, $message, $headers)) {
  echo "SUCCESS";
} else {
  echo "ERROR";
}
```

Then execute the script by going on http://localhost/mailhog.php

Now look at the WebUI of Mailhog at http://127.0.0.1:8025/

![image](https://user-images.githubusercontent.com/1951866/79395617-4f378e00-7f7a-11ea-9f01-dd5ed32f3d6a.png)

**Comment by iansebryk** [comment]
perfect.  thanks Max.  gonna have to send you a six-pack of something one of these days...  ;D
