### ISSUE TITLE
Neard error during start after change installation folder

### ISSUE THREAD

**Issue by myspulin** [neard/neard#452]
### Behaviour

When installation folder of neard changed I cannot start it any more.

See the message:

![neard vbs error](https://user-images.githubusercontent.com/4679494/79635389-d51d2a00-8170-11ea-8929-54613ffa23ad.png)

The problem is in neard\core\scripts\execSilent.vbs and the nonexisted path given by old symlinks.

When I deleted old symlinks neard started again whith no errors.

#### Steps to reproduce this issue

1. Install neard to some folder (D:\Programs)
2. Start it, to create symlinks "Current"
3. Move the neard folder to another path (D:\)

#### Expected behaviour

To recreate symlinks for current path.

#### Actual behaviour

Neard cannot start.

### Configuration

* Neard 1.7.1
* Operating system: Win 10

Thank you for the new version, good job!

Lukas

**Comment by crazy-max** [comment]
@myspulin Fixed in [1.7.2](https://neard.io/news/2020-04-19-neard-1.7.2-released/)

**Comment by myspulin** [comment]
Hi, I tried the 1.8 version and had the same issue, it cannot start until I delete all symlinks from previous path. Can you please check, thanks.
