### ISSUE TITLE
since Adminer is just a file, why does upgrading it bork Neard?

### ISSUE THREAD

**Issue by iansebryk** [neard/neard#455]
#### Steps to reproduce this issue

1. download Adminer 4.7.6
2. place in ~\neard\neard-1.8.0\apps\adminer\adminer4.7.6\
3. modify neard.conf with new version
4. start Neard
5. explode

#### Expected behaviour

Neard should start with no issue.  Adminer is a FILE.

#### Actual behaviour

All modules fail to load:

![neard-postgre-new-error-00](https://user-images.githubusercontent.com/1943574/80722664-d9c0d700-8abc-11ea-9f28-62275068b051.jpg)

### Configuration

Neard 1.7.1

yeah, yeah, @crazy-max ... i know: upgrade!  😝 but i can't for two weeks until this project is done (then we tackle upgrae AND the PostgreSQL issue...).  but Adminer is throwing errors that 4.7.6 fixes.  so i thought it would be an easy small upgrade.  nope.  my system is haunted....  😱

**Comment by N6REJ** [comment]
adminer & phpmyadmin are the same thing so why both in applications?

**Comment by iansebryk** [comment]
while they *basicaly* do the same thing, they aren't *at all* the same thing.  they each have different features.

**Comment by N6REJ** [comment]
only thing I can go by is what they say.. 
![image](https://user-images.githubusercontent.com/1850089/80926725-9c7b7400-8d5e-11ea-9488-b3a7bcbb43a7.png)

**Comment by N6REJ** [comment]
sorry, MINadmin.. old fart eyes

**Comment by iansebryk** [comment]
no worries.  😆  i have blind moments too!

**Comment by iansebryk** [comment]
poke. poke.  poke.

**Comment by iansebryk** [comment]
i managed to get this running (see the separate issue i just commented on) but don't know where the other files come from.  i run adminer on one of my other linux servers and it's just the one file.  so the extra .css/.php files is a bit of a mystery.  IF convenient, i would like to slake my curiosity, but it's no longer important now that i have 4.7.7 running without issue.
