### ISSUE TITLE
PHP 7.2.34, 7.3.25, 7.4.13, 8.0.0

### ISSUE THREAD

**Issue by LEO33SoFo** [neard/neard#458]
Can i request **PHP** v7.4.7?

**Comment by N6REJ** [comment]
@crazy-max we really need php 8 asap please.

**Comment by crazy-max** [comment]
@N6REJ This is an open source project. Feel free to open a PR. Thanks.

**Comment by N6REJ** [comment]
I was attempting to do the upgrade a month or so ago and sent you an enquiry as I was having difficulties but got no response.  I'll look into it again.

**Comment by myspulin** [comment]
Hi, I have intalled php 8, how to do it:

At first install new version of Apache 2.4.46, link: https://github.com/neard/neard/issues/457

1. Open https://windows.php.net/download, download zip file php-8.0.0-Win32-vs16-x86.zip
2. Under neard\bin\php create folder "php8.0.0"
3. Copy all files from zipfile to the new folder
4. Copy from previos installed PHP version files "neard.conf" and "php.ini"
5. Edit neard.conf file:

`
phpVersion = "8.0.0"
phpCliExe = "php.exe"
phpCliSilentExe = "php-win.exe"
phpConf = "php.ini"
phpPearExe = "pear/pear.bat"

apache24 = "php8apache2_4.dll"

bundleRelease = "rMy"`

6. Edit php.ini file and replace all strings (php7.4.4) to php8.0.0 and save it
7. Edit the file neard\core\classes\bins\class.bin.php.php and find function getTsDll and update it to handle version 8

` public function getTsDll($phpVersion = null) {
        $phpVersion = $phpVersion == null ? $this->getVersion() : $phpVersion;
        $currentPath = str_replace('php' . $this->getVersion(), 'php' . $phpVersion, $this->getCurrentPath());

        if (file_exists($currentPath . '/php5ts.dll')) {
            return 'php5ts.dll';
        } elseif (file_exists($currentPath . '/php7ts.dll')) {
            return 'php7ts.dll';
        } elseif (file_exists($currentPath . '/php8ts.dll')) {
            return 'php8ts.dll';
        }

        return false;
    }
`
7. Edit the file neard\core\classes\bins\class.bin.apache.php

`
on the line 230 replace the code

$apachePhpModuleName = $tsDll !== false ? substr($tsDll, 0, 4) . '_module' : null;

by

if((int) substr($neardBins->getPhp()->getVersion(), 0, 1) === 8){
   //PHP 8 version
  $apachePhpModuleName = $tsDll !== false ? 'php_module' : null;
}else{
  //Other versions
  $apachePhpModuleName = $tsDll !== false ? substr($tsDll, 0, 4) . '_module' : null
}

after the line 279

 '/^#?LoadModule\sphp._module\s.*/' => ($neardBins->getPhp()->isEnable() ? '' : '#') . 'LoadModule ' . $apachePhpModuleName . ' "' . $neardBins->getPhp()->getSymlinkPath() . '/' . $apachePhpModuleDll . '"',

add

'/^#?LoadModule\sphp_module\s.*/' => ($neardBins->getPhp()->isEnable() ? '' : '#') . 'LoadModule ' . $apachePhpModuleName . ' "' . $neardBins->getPhp()->getSymlinkPath() . '/' . $apachePhpModuleDll . '"',

`
8. Edit file php.ini and find all strings with the older php version and replace it with php8.0.0
9. Restart Neard and switch the new version of PHP

There are some missing extensions, you can disable it or download and install. Xdebug is easy one.

@crazy-max Can I help with modules?

Lukas

**Comment by N6REJ** [comment]
@myspulin do we need apache updated for 8 to work?

**Comment by myspulin** [comment]
> @myspulin do we need apache updated for 8 to work?

No, you can use also the default 2.4.41 version.

**Comment by N6REJ** [comment]
@myspulin whats the fix for xdebug?  It's pretty important for me.

**Comment by N6REJ** [comment]
> after the line 279
> 
> ` '/^#?LoadModule\sphp._module\s.*/' => ($neardBins->getPhp()->isEnable() ? '' : '#') . 'LoadModule ' . $apachePhpModuleName . ' "' . $neardBins->getPhp()->getSymlinkPath() . '/' . $apachePhpModuleDll . '"',`
> 
> add
> 
> `'/^#?LoadModule\sphp_module\s.*/' => ($neardBins->getPhp()->isEnable() ? '' : '#') . 'LoadModule ' . $apachePhpModuleName . ' "' . $neardBins->getPhp()->getSymlinkPath() . '/' . $apachePhpModuleDll . '"',`

@myspulin you sure thats right?  It's the same exact code.

**Comment by N6REJ** [comment]
btw, your fix doesn't work @myspulin .. try it on a clean copy of neard and you will see.  Spent almost 2hrs trying to get it to work.

**Comment by myspulin** [comment]
> > after the line 279
> > ` '/^#?LoadModule\sphp._module\s.*/' => ($neardBins->getPhp()->isEnable() ? '' : '#') . 'LoadModule ' . $apachePhpModuleName . ' "' . $neardBins->getPhp()->getSymlinkPath() . '/' . $apachePhpModuleDll . '"',`
> > add
> > `'/^#?LoadModule\sphp_module\s.*/' => ($neardBins->getPhp()->isEnable() ? '' : '#') . 'LoadModule ' . $apachePhpModuleName . ' "' . $neardBins->getPhp()->getSymlinkPath() . '/' . $apachePhpModuleDll . '"',`
> 
> @myspulin you sure thats right? It's the same exact code.

It is not the same code, there is "sphp_module" instead of "sphp._module"

**Comment by myspulin** [comment]
> btw, your fix doesn't work @myspulin .. try it on a clean copy of neard and you will see. Spent almost 2hrs trying to get it to work.

Doesn't work means what exactly? Can you provide some errors, logs? Thanks.

**Comment by N6REJ** [comment]
@myspulin 
1) pear is missing completely
2) neard fails to fully start.
I'm going to try a 2nd clean install of neard and see if that makes any difference.

**Comment by crazy-max** [comment]
https://neard.io/modules/php/#releases
