### ISSUE TITLE
None of the consoles will start: all fail with 'undefined tab' error

### ISSUE THREAD

**Issue by iansebryk** [neard/neard#464]
#### Steps to reproduce this issue

1. open the taskbar menu
2. choose any running application or tool (eg. NodeJS)
3. select 'Console' from the submenu

#### Expected behaviour

> a console for the relevant tool/app will launch with proper environment set

#### Actual behaviour

> error is thrown and, once the OK button is clicked, the console that starts recognizes none of the relevant commands

### Configuration

* Neard version 1.8.0 - BRAND NEW INSTALL
* Operating system: Windoze 10 Pro

### Logs

[Console-Launch-Failure.zip](https://github.com/neard/neard/files/4961715/Console-Launch-Failure.zip)

![2020-07-22_neard_consoleFailure](https://user-images.githubusercontent.com/1943574/88213025-6c34ca80-cc15-11ea-933f-57444aab6cbe.jpg)

![2020-07-22_neard_consoleFailure2](https://user-images.githubusercontent.com/1943574/88213048-735bd880-cc15-11ea-8347-f18af0a0bef7.jpg)

FFS, i'm beginning to think my system is just bloody haunted...  ☹️

**Comment by crazy-max** [comment]
@iansebryk Yeah looks like your environment is corrupted. You can try the latest release (1.8.2).
