### ISSUE TITLE
1.8.2 fails to load

### ISSUE THREAD

**Issue by N6REJ** [neard/neard#471]
### Behaviour
If you do the replacement steps outlined in the 1.8.2 release ( moving core & aliases ) you get
![image](https://user-images.githubusercontent.com/1850089/102083099-a8411580-3dd8-11eb-9a29-1cecb7361cd5.png)
when you attempt to start.
If you run 1.8.2 itself with no changes you just get loading...
![image](https://user-images.githubusercontent.com/1850089/102083201-cf97e280-3dd8-11eb-8752-bd2997edc5e4.png)

just an fyi, 1.8.2 doesn't contain the new php versions...
![image](https://user-images.githubusercontent.com/1850089/102083327-fb1acd00-3dd8-11eb-9fa4-23a5130e30a1.png)

#### Steps to reproduce this issue
see above

#### Expected behaviour

neard starts as always

#### Actual behaviour
error thrown.

### Configuration

previous: 1.8.0
current: 1.8.2

* Operating system: 
win 10 x64 pro

### Logs
[logs.zip](https://github.com/neard/neard/files/5688873/logs.zip)

**Comment by crazy-max** [comment]
@N6REJ Debug does not seem enable in your conf (>* Change the `logsVerbose` variable to the value `2` in the `neard.conf` file.)

**Comment by N6REJ** [comment]
logs were already set to "2" logsVerbose = "2".
I'll try basic.

**Comment by N6REJ** [comment]
must have been a pathing issue.. after using basic it all works.
