### ISSUE TITLE
[Feature request] Set default editor for files (.ini, .conf, etc) instead of notepad

### ISSUE THREAD

**Issue by Ares9323** [neard/neard#474]
Hi! I started using Neard few days ago, I was using Wamp before and during installation it requires to set the default browser and file editor (default are notepad and internet explorer like in Neard)

I've been able to set the default browser by right clicking the icon in the taskbar but I couldn't find the editor setting.
Obviously I set vscode as my default editor for both extensions I mentioned in the title.

Thanks in advance, and thanks for your great work

**Comment by bugnumber9** [comment]
You can set the default editor in neard.conf file. Check the first section, the option is there. For example, I've set the default editor to Notepad++ like this:
`notepad = "C:\Program Files (x86)\Notepad++\notepad++.exe"`

**Comment by crazy-max** [comment]
@Ares9323 https://neard.io/doc/get-started/#configuration
