### ISSUE TITLE
Overwriting of mysqli.default_port in php.ini

### ISSUE THREAD

**Issue by bugnumber9** [neard/neard#475]
I've set MariaDB port to 3306 via Neard menu. Not using MySQL at all.
Then I edited php.ini and set mysqli.default_port = 3306
However, every time I start Neard again it overwrites that value and sets it back to 3307

**Comment by bugnumber9** [comment]
I solved the issue for the time being by making php.ini read only.

**Comment by crazy-max** [comment]
@bugnumber9 `mysql.default_port` and `mysqli.default_port` in `php.ini` is handled by Neard and reflects the port used by the [MySQL module](https://neard.io/modules/mysql/) service on Neard. So in your case MySQL has port `3307` configured. Change it to 3306 and the value in the `php.ini` will be updated.

**Comment by bugnumber9** [comment]
Right, but why is this necessary? :)
I mean, we have the choice to run both MySQL and MariaDB or only one of those. We can set ports for each, etc.
I originally wanted to run both, but wanted MariaDB on port 3306, MySQL on port 3307, and also wanted PHP to default to MariaDB while leaving MySQL for one app where I'd specify DB port explicitly.
