### ISSUE TITLE
Cosmetic french traduction - missed "r" in "neard"

### ISSUE THREAD

**Issue by alain01** [neard/neard#476]
https://github.com/neard/neard/blob/c4b1cdba7a8546b6550d57285f81f2daee3a94d4/core/langs/french.lng#L357

> homepageQuestionsText = "Si vous rencontrez des problèmes ou si vous avez des idées pour faire évoluer Nead, postez un ticket sur GitHub !"

doit devenir
> homepageQuestionsText = "Si vous rencontrez des problèmes ou si vous avez des idées pour faire évoluer Neard, postez un ticket sur GitHub !"

Manque le "r" à neard, un comble ;-)

Note : Excellent outil, de loin le meilleur WAMP ! 
Bientôt un tuto sera disponible sur l'utilisation de neard / des virtuals host pour le CMS XOOPS (https://www.monxoops.fr/)

**Comment by crazy-max** [comment]
Salut @alain01,

> Cosmetic french traduction - missed "r" in "neard"

Merci pour avoir détecté cette typo! Si tu peux ouvrir une PR pour corriger ça ce serait top merci!

> Note : Excellent outil, de loin le meilleur WAMP !

Ravi que cette app te plaise!

> Bientôt un tuto sera disponible sur l'utilisation de neard / des virtuals host pour le CMS XOOPS (https://www.monxoops.fr/)

Ouah excellent, n'hésite pas si tu as des questions pour ton article :)
