### ISSUE TITLE
Can't start neard.exe

### ISSUE THREAD

**Issue by jmevalentin** [neard/neard#479]
#### Steps to reproduce this issue

1. Extract the downloaded zip file.
2. Locate and run neard.exe (located in **base/neard** directory)

#### Expected behaviour

> The application should run

#### Actual behaviour

> I get the following popup error: 
` Exception Exception in module neard.exe at 000F15A0. Could not execcute run action: The system cannot find the file specified`

### Configuration

* Neard version and the previous version in case of upgrade: 
* Operating system: 
According to the changelog, this is version 1.8.2
### Logs

>* Close Neard.
>* Change the `logsVerbose` variable to the value `2` in the `neard.conf` file.
>* Launch Neard and reproduce your issue.
>* Close Neard.
>* Zip the `logs` folder and the `core/tmp` folder.
>* [Drag and drop](https://help.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) the zip archive here.

No log file is created as it appears the app can't create them since it can't start

**Comment by crazy-max** [comment]
@jmevalentin 

> 1. Extract the downloaded zip file.
> 2. Locate and run neard.exe (located in **base/neard** directory)

You have download the git source repository and not the release artifact. Documentation to download and install Neard is available on the official website: https://neard.io/doc/get-started/
