### ISSUE TITLE
Smart tutorial for Neard, then use it with XOOPS (french tutorial)

### ISSUE THREAD

**Issue by alain01** [neard/neard#482]
Here a tutorial in french language to : 
- Install Neard,
- Configure,
- Change parameters
- Add MariaDB,
- Add PHP versions
- Add Virtual Host

Then use it with the CMS XOOPS.
![Neard + XOOPS](https://www.monxoops.fr/uploads/xmtutorial/images/tutorial/outils-xoops-neard.png)
URL : https://www.monxoops.fr/modules/xmtutorial/tutorial.php?tutorial_id=11

**Comment by crazy-max** [comment]
Hi @alain01 

That's great thanks for that! I will add a link to your tutorial on the website. Thanks!

**Comment by alain01** [comment]
Didnt find the link to the tutorial.
Number of views in this tutorial: 445

**Comment by alain01** [comment]
Up
Number of views in this tutorial: close to 800
